name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v7
    - name: Install packages
      run: sudo apt-get -y install ocaml ocaml-dune
    - name: Build
      run: dune build
    - name: Test
      run: |
        dune test
        make -C examples
