name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup OCaml
      uses: avsm/setup-ocaml@v2
      with:
        ocaml-compiler: 5.0
    - name: Install dependencies
      run: opam install . --deps-only --with-test
    - name: Build
      run: opam exec -- dune build
    - name: Test
      run: opam exec -- dune runtest
